name: 🔨 Build firmware

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    build-check:
        name: Build
        strategy:
            matrix:
                os: [ubuntu-latest]
                compiler_version:
                    [9-2019-q4, 10-2020-q4, 10-2021.07, 10.3-2021.10]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            # Install dependencies
            - name: Install arm-none-eabi-gcc ${{ matrix.compiler_version }}
              uses: fiam/arm-none-eabi-gcc@v1
              with:
                  # The arm-none-eabi-gcc release to use
                  release: "${{ matrix.compiler_version }}"
            - name: Get latest CMake and ninja
              # Using 'latest' branch, the most recent CMake and ninja are installed.
              uses: lukka/get-cmake@latest
            # Build the project and flash it
            - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc-toolchain.cmake .. && make -j`nproc`
# Available versions using the github action: 10-2020-q4,9-2020-q2,9-2019-q4,8-2019-q3,8-2018-q4,7-2018-q2,7-2017-q4,6-2017-q2,6-2017-q1,6-2016-q4,5-2016-q3,5-2016-q2,5-2016-q1,5-2015-q4,4.9-2015-q3,4.9-2015-q2,4.9-2015-q1,4.9-2014-q4,4.8-2014-q3,4.8-2014-q2,4.8-2014-q1,4.7-2014-q2,4.8-2013-q4,4.8-2013-q4-darwin,4.7-2013-q3,4.7-2013-q2,4.7-2013-q1,4.7-2012-q4