name: 🔨 Build firmware

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    build-check:
        name: Build
        strategy:
            matrix:
                os: [ubuntu-latest]
                compiler_version:
                    [9-2019-q4, 10-2020-q4, 10-2021.07, 10.3-2021.10]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            # Install dependencies
            - name: Install arm-none-eabi-gcc ${{ matrix.compiler_version }}
              uses: fiam/arm-none-eabi-gcc@v1
              with:
                  # The arm-none-eabi-gcc release to use
                  release: "${{ matrix.compiler_version }}"
            - name: Get latest CMake and ninja
              # Using 'latest' branch, the most recent CMake and ninja are installed.
              uses: lukka/get-cmake@latest
            # Build the project and flash it
            - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc-toolchain.cmake .. && make -j`nproc`
