name: 📜 Check CHANGELOG update on PR

on:
    pull_request:
        branches:
            - "develop"

jobs:
    formatting-check:
        name: 📜 Check CHANGELOG update on PR
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check changelog diff compared to target branch
              # - run: git diff --exit-code --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA .gitignore &&  exit 1 || exit 0
              # git diff --exit-code $GITHUB_HEAD_REF $GITHUB_BASE_REF -- CHANGELOG.md
              run: |
                  git fetch origin $GITHUB_HEAD_REF
                  git diff --exit-code ..$GITHUB_HEAD_REF CHANGELOG.md
