# Run clang-tidy
name: 👔 Check clang-tidy

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    checkout-and-check-formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run clang-tidy linting check
              uses: HorstBaerbel/action-clang-tidy@1.2
              # These are optional (defaults displayed)
              with:
                  scandir: "src"
                  builddir: "build"
                  # excludedirs: ""
                  extensions: "c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx"
                  # cmakeoptions: ""
