name: 👔 Check clang-tidy

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    linting-check:
        name: Linting Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run clang-format formatting check
            - run: sudo apt-get update
            - run: sudo apt-get install -y clang-tidy
