name: 🛠 Build and flash on hardware

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    formatting-check:
        name: Hardware flash
        runs-on: self-hosted
        container:
            image: john15321/stm-development-amd64:alpine
        steps:
            - uses: actions/checkout@v2
            - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc-toolchain.cmake .. && make -j`nproc` && st-flash write OBC.bin 0x8000000
