name: 🔍 Check linting

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    cpp-linter:
        name: 🔍 Linting Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # - name: Install arm-none-eabi-gcc
            #   uses: carlosperate/arm-none-eabi-gcc-action@v1
            #   with:
            #       release: "latest"
            # - name: Build the project and command json
            #   run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi-gcc-toolchain.cmake .. && make -j`nproc` && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
            - name: Install cppcheck
              run: sudo apt-get install -y cppcheck
            - name: Run cppcheck
              run: cppcheck -ibuild/CMakeFiles/ -iprj/ -i3rdparty -isrc/bsp/ --enable=all --inconclusive --library=posix  . -I ./3rdparty -I prj -I ./src/bsp/  --error-exitcode=1
